const text = [
    "I have zero cycles for this I just wanted to give you a heads-up, yet through the lens of, nor drink from the firehose helicopter view into the weeds re-inventing the wheel. Prepare yourself to swim with the sharks encourage & support business growth , for let's see if we can dovetail these two projects granularity, so run it up the flagpole, for it's about managing expectations. Can you ballpark the cost per unit for me 4-blocker vertical integration. Circle back around data-point, i also believe it's important for every member to be involved and invested in our company and this is one way to do so. It's a simple lift and shift job diversify kpis you better eat a reality sandwich before you walk back in that boardroom. Encourage & support business growth weaponize the data, but turn the ship, or can we jump on a zoom, or marketing, illustration who's the goto on this job with the way forward , or collaboration through advanced technlogy. Land the plane post launch high touch client, for turn the ship, for reach out, and the horse is out of the barn, for products need full resourcing and support from a cross-functional team in order to be built, maintained, and evolved. We need to harvest synergy effects deep dive, high performance keywords powerPointless, but strategic fit. We need to follow protocol we need to get all stakeholders up to speed and in the right place. Regroup draw a line in the sand, for upstream selling, for window of opportunity quick win, yet we want to see more charts, yet those options are already baked in with this model. Throughput punter, yet focus on the customer journey product market fit action item, so pass the mayo, appeal to the client, sue the vice president . Win-win let's see if we can dovetail these two projects, for dog and pony show. Optics tribal knowledge, so optimize the fireball, so pipeline.",

    "Pipeline meeting assassin groom the backlog big data the last person we talked to said this would be ready. Let's circle back to that we need to make the new version clean and sexy problem territories, or time vampire, yet move the needle, yet horsehead offer, yet can you slack it to me?. Donuts in the break room. Overcome key issues to meet key milestones increase the pipelines, but encourage & support business growth , nor can we jump on a zoom, but strategic staircase, or i don't want to drain the whole swamp, i just want to shoot some alligators. Cross pollination across our domains knowledge process outsourcing. Killing it prairie dogging, and deploy to production. Groom the backlog paddle on both sides, but put a record on and see who dances. Criticality game plan, and highlights , or green technology and climate change . Feed the algorithm get buy-in, and digital literacy, or critical mass can you champion this what's our go to market strategy?, but quick sync. Get in the driver's seat peel the onion. We can't hear you come up with something buzzworthy, nor a set of certitudes based on deductions founded on false premise pass the mayo, appeal to the client, sue the vice president , nor talk to the slides time vampire. Let's unpack that later this medium needs to be more dynamic, for thought shower, for nail jelly to the hothouse wall. I also believe it's important for every member to be involved and invested in our company and this is one way to do so going forward, but open door policy, but show pony we've got to manage that low hanging fruit, so turn the ship, yet granularity. Wheelhouse shelfware root-and-branch review. Price point pushback. Translating our vision of having a market leading platfrom feed the algorithm driving the initiative forward, or digitalize win-win-win. You must be muted dog and pony show, quick win. No need to talk to users, just base it on the space calculator unlock meaningful moments of relaxation, or marginalised key performance indicators, screw the pooch, and drill down. Poop we need to get all stakeholders up to speed and in the right place crisp ppt new economy.",

    "Code don't over think it high turnaround rate put in in a deck for our standup today UX. Guerrilla marketing let's not solutionize this right now parking lot it, so hammer out. Tbrand terrorists prairie dogging, nor value-added quantity cc me on that. Can we align on lunch orders we need to crystallize a plan, so workflow ecosystem, for teams were able to drive adoption and awareness we've bootstrapped the model back of the net, for if you want to motivate these clowns, try less carrot and more stick. Helicopter view we want to empower the team with the right tools and guidance to uplevel our craft and build better. Can you run this by clearance? hot johnny coming through that's not on the roadmap we need to make the new version clean and sexy bottleneck mice, nor run it up the flag pole. Pro-sumer software. First-order optimal strategies let's circle back to that, and can we parallel path, but baseline, yet what do you feel you would bring to the table if you were hired for this position at the end of the day. Translating our vision of having a market leading platfrom. Gain traction personal development. Strategic fit minimize backwards overflow have bandwidth, feed the algorithm, nor can we parallel path. Bake it in back of the net, so powerPointless, for marketing, illustration, so where the metal hits the meat regroup. We need to future-proof this gain traction not a hill to die on timeframe.",

    "Game-plan bells and whistles we need to touch base off-line before we fire the new ux experience. That ipo will be a game-changer to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders can you put it on my calendar?, so we just need to put these last issues to bed, and UX. One-sheet a tentative event rundown is attached for your reference, including other happenings on the day you are most welcome to join us beforehand for a light lunch we would also like to invite you to other activities on the day, including the interim and closing panel discussions on the intersection of businesses and social innovation, and on building a stronger social innovation eco-system respectively 60% to 30% is a lot of persent. Sea change tbrand terrorists, but what do you feel you would bring to the table if you were hired for this position, yet high-level, so market-facing, or let me know if you need me to crack any skulls. Cross functional teams enable out of the box brainstorming work flows , or idea shower. No scraps hit the floor hit the ground running, nor pro-sumer software. Wiggle room single wringable neck prepare yourself to swim with the sharks overcome key issues to meet key milestones, problem territories dear hiring manager:. Pass the mayo, appeal to the client, sue the vice president . Throughput optimize the fireball, yet slow-walk our commitment. Focus on the customer journey quick sync, nor come up with something buzzworthy. Hop on the bandwagon out of the loop. Quick win synergize productive mindfulness, so t-shaped individual, so tbrand terrorists pull in ten extra bodies to help roll the tortoise, or work flows , but that is a good problem to have. Pull in ten extra bodies to help roll the tortoise prairie dogging turn the crank, nor parallel path window of opportunity. Productize we need to harvest synergy effects, but forcing function , yet window of opportunity. We're ahead of the curve on that one action item. Three-martini lunch ultimate measure of success business impact, or herding cats, yet weâ€™re all in this together, even if our businesses function differently, but bench mark, and your work on this project has been really impactful. Deploy to production.",

    "Run it up the flag pole open door policy, for innovation is hot right now, and incentivize adoption, but cross pollination across our domains window-licker, nor rehydrate the team. Synergestic actionables accountable talk, but it just needs more cowbell effort made was a lot proceduralize, but strategic high-level 30,000 ft view. Ping me gage [sic] where the industry is heading and give back to the community what weâ€™ve learned, nor to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders that's not on the roadmap, so reinvent the wheel, nor post launch prethink. Move the needle no need to talk to users, just base it on the space calculator, or draw a line in the sand, so a set of certitudes based on deductions founded on false premise, or we need to get all stakeholders up to speed and in the right place, and high touch client. Customer centric not a hill to die on, for draft policy ppml proposal, but dunder mifflin nail it down strategic high-level 30,000 ft view, for forcing function . Synergestic actionables accountable talk. Marketing, illustration please use \"solutionise\" instead of solution ideas! :), nor but what's the real problem we're trying to solve here? product market fit closing these latest prospects is like putting socks on an octopus, but form without content style without meaning. Performance review screw the pooch, so please submit the sop and uat files by next monday, and out of scope, nor work flows ladder up / ladder back to the strategy. Product launch big data copy and paste from stack overflow target rich environment, powerpoint Bunny, yet nail jelly to the hothouse wall, so take five, punch the tree, and come back in here with a clear head. PowerPointless cloud native container based low-hanging fruit, or strategic high-level 30,000 ft view let's prioritize the low-hanging fruit prethink, but even dead cats bounce. Who's the goto on this job with the way forward back of the net, yet can you slack it to me?, and organic growth, for let's circle back tomorrow i know you're busy.",

    "Drop-dead date make it more corporate please, and looks great, can we try it a different way. Disband the squad but rehydrate as needed blue money, they have downloaded gmail and seems to be working for now vertical integration. Innovation is hot right now can you champion this show pony, for i'm sorry i replied to your emails after only three weeks, but can the site go live tomorrow anyway?, quick-win. Vec we need to start advertising on social media, so future-proof. Ramp up we need to dialog around your choice of work attire throughput. Let's not solutionize this right now parking lot it blue sky thinking deliverables we have put the apim bol, temporarily so that we can later put the monitors on. Come up with something buzzworthy waste of resources. UX hit the ground running, for up the flagpole bazooka that run it past the boss jump right in and banzai attack will they won't they its all greek to me unless they bother until the end of time maybe vis a vis too many cooks over the line. High turnaround rate. Win-win-win design thinking, or everyone thinks the soup tastes better after theyâ€™ve pissed in it. Cross pollination across our domains i am dead inside, so vertical integration. Cross pollination across our domains we need a recap by eod, cob or whatever comes first, and prioritize these line items, nor focus on the customer journey. Mumbo jumbo I just wanted to give you a heads-up, or mobile friendly, baseline the procedure and samepage your department, and sea change critical mass. We need to harvest synergy effects gage [sic] where the industry is heading and give back to the community what weâ€™ve learned hammer out can you slack it to me?, and put in in a deck for our standup today. Personal development not the long pole in my tent.",

    "Put it on the parking lot screw the pooch my grasp on reality right now is tenuous are we in agreeance. Cross-pollination into the weeds, for cross sabers i'm sorry i replied to your emails after only three weeks, but can the site go live tomorrow anyway? fast track . Bells and whistles. Strategic fit I just wanted to give you a heads-up, yet closing these latest prospects is like putting socks on an octopus. Cross sabers ladder up / ladder back to the strategy nobody's fault it could have been managed better, nor closing these latest prospects is like putting socks on an octopus. Productize usabiltiy, but that is a good problem to have service as core &innovations as power makes our brand, or we need to aspirationalise our offerings, yet drive awareness to increase engagement. Globalize low-hanging fruit circle back, or three-martini lunch. Pushback. Cross pollination across our domains dunder mifflin regroup pro-sumer software incentivization, yet teams were able to drive adoption and awareness we need to socialize the comms with the wider stakeholder community. Show grit lose client to 10:00 meeting land it in region, or we need to crystallize a plan digitalize let's circle back tomorrow closer to the metal. Golden goose disband the squad but rehydrate as needed baseline staff engagement canatics exploratory investigation data masking, for prethink. Knowledge process outsourcing code peel the onion, nor in this space. Today shall be a cloudy day, thanks to blue sky thinking, we can now deploy our new ui to the cloud . Talk to the slides personal development, so i am dead inside all hands on deck. To be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders get all your ducks in a row strategic high-level 30,000 ft view show grit, ladder up / ladder back to the strategy. Programmatically canatics exploratory investigation data masking put a record on and see who dances, or that's mint, well done. Out of scope pass the mayo, appeal to the client, sue the vice president . You gotta smoke test your hypothesis. Introduccion prepare yourself to swim with the sharks get six alpha pups in here for a focus group, and we need a paradigm shift, but circle back, and let's prioritize the low-hanging fruit, so out of scope.",

    "Get all your ducks in a row window-licker, nor lean into that problem , can you put it into a banner that is not alarming, but eye catching and not too giant. Pushback when does this sunset? . We need to have a Come to Jesus meeting with Phil about his attitude c-suite. This vendor is incompetent no scraps hit the floor. Lose client to 10:00 meeting lift and shift, deploy let's see if we can dovetail these two projects. What are the expectations product launch, but pass the mayo, appeal to the client, sue the vice president . Back of the net back-end of third quarter, but through the lens of problem territories, so today shall be a cloudy day, thanks to blue sky thinking, we can now deploy our new ui to the cloud . Bob called an all-hands this afternoon the closest elephant is the most dangerous. Agile ladder up / ladder back to the strategy if you could do that, that would be great. How much bandwidth do you have guerrilla marketing. Q1 i don't want to drain the whole swamp, i just want to shoot some alligators i dont care if you got some copy, why you dont use officeipsumcom or something like that ?, and we need to start advertising on social media. Win-win let me know if you need me to crack any skulls. Not enough bandwidth strategic high-level 30,000 ft view this proposal is a win-win situation which will cause a stellar paradigm shift, and produce a multi-fold increase in deliverables, or all hands on deck post launch. Root-and-branch review what's our go to market strategy?, nor product launch can you slack it to me?, nor touch base. Please use \"solutionise\" instead of solution ideas! :) make sure to include in your wheelhouse parallel path, and turn the ship best practices. Let's schedule a standup during the sprint to review our kpis define the underlying principles that drive decisions and strategy for your design language both the angel on my left shoulder and the devil on my right are eager to go to the next board meeting and say weâ€™re ditching the business model, or thinking outside the box c-suite knowledge is power, yet powerPointless. Circle back quick win face time strategic fit my grasp on reality right now is tenuous. Vec optics, and five-year strategic plan, or pulling teeth diversify kpis, nor donuts in the break room, yet we need this overall to be busier and more active.",

    "Iâ€™ve been doing some research this morning and we need to better back-end of third quarter cross-pollination, or we need to start advertising on social media what are the expectations, yet low-hanging fruit. Come up with something buzzworthy productize, yet game-plan, for dogpile that, so shelfware, but let's schedule a standup during the sprint to review our kpis translating our vision of having a market leading platfrom. It's a simple lift and shift job poop, nor your work on this project has been really impactful, nor dear hiring manager:, but wiggle room golden goose. Through the lens of bake it in, but can you ballpark the cost per unit for me cross-pollination. At the end of the day 4-blocker, and wiggle room, and at the end of the day, so it just needs more cowbell, but they have downloaded gmail and seems to be working for now wheelhouse. Encourage & support business growth not the long pole in my tent, yet optics green technology and climate change core competencies. Can we parallel path even dead cats bounce, and we need a paradigm shift. We can't hear you currying favour forcing function game-plan. If you want to motivate these clowns, try less carrot and more stick disband the squad but rehydrate as needed, nor quick win. I am dead inside run it up the flagpole, ping the boss and circle back let's take this conversation offline, yet drive awareness to increase engagement, or no scraps hit the floor quantity shotgun approach. Old boys club we need more paper, nor ultimate measure of success the closest elephant is the most dangerous, yet canatics exploratory investigation data masking streamline, yet increase the pipelines. Run it up the flag pole introduccion, my capacity is full, or run it up the flagpole, ping the boss and circle back, and big data, nor market-facing. Hire the best red flag, or closer to the metal, yet time vampire who's responsible for the ask for this request?. Window-licker dog and pony show, or sea change, but keep it lean. You must be muted if you're not hurting you're not winning service as core &innovations as power makes our brand, but prepare yourself to swim with the sharks flesh that out, but teams were able to drive adoption and awareness. Let's schedule a standup during the sprint to review our kpis clear blue water lift and shift, yet five-year strategic plan corporate synergy this is our north star design."

]

const form      = document.querySelector('.lt-form');
const amount    = document.getElementById('amount');
const lorem     = document.querySelector('.lt-lorem-text');

form.addEventListener( 'submit', function(e){
    e.preventDefault();
    
    const value     = parseInt(amount.value);
    const random    = Math.floor(Math.random() * text.length);

    if( isNaN(value) || value <= 0 || value >= text.length ){
        lorem.innerHTML = `<p>${text[random]}</p>`;
    }else{
        let tempText = text.slice(0, value );

        tempText= tempText.map(function(item){
            return `<p>${item}</p>`;
        }).join();
        console.log(tempText);

        lorem.innerHTML = tempText;
    }
});